### ISSUE TITLE
编译失败。 jemalloc没有提交

### ISSUE THREAD

**Issue by samuelyao314** [WeichengCao/game_dev#1]
samuel@samhost:~/src/game_dev/skynet$ make linux
make all PLAT=linux SKYNET_LIBS="-lpthread -lm -ldl -lrt" SHARED="-fPIC --shared" EXPORT="-Wl,-E" MALLOC_STATICLIB="3rd/jemalloc/lib/libjemalloc_pic.a" SKYNET_DEFINES=""
make[1]: Entering directory '/home/samuel/src/game_dev/skynet'
git submodule update --init
fatal: 在 .gitmodules 中没有发现路径 'skynet/3rd/jemalloc' 的子模组映射
Makefile:35: recipe for target '3rd/jemalloc/autogen.sh' failed
make[1]: *** [3rd/jemalloc/autogen.sh] Error 128
make[1]: Leaving directory '/home/samuel/src/game_dev/skynet'

**Comment by WeichengCao** [comment]
cd skynet/3rd/ && git clone https://github.com/jemalloc/jemalloc.git

**Comment by samuelyao314** [comment]
你好。 这2个问题我自己已经解决了。 我的意思是， 你应该在代码库修改。不应该让每个人都clone后还要重新解决这个问题。这样就可以节省大家的时间啊
