### ISSUE TITLE
启动失败。

### ISSUE THREAD

**Issue by samuelyao314** [WeichengCao/game_dev#2]
samuel@samhost:~/src/game_dev$ ./skynet/skynet config/gs_config.lua 
Can't launch logger service

因为项目默认是没有 log目录。启动就会失败
samuel@samhost:~/src/game_dev$ cat config/gs_config.lua 
logger = "log/gs.log"

**Comment by WeichengCao** [comment]
log文件每次启动都会有diff，因此我没有把这部分内容加入到git版本中，自己创建一个log文件夹就好了
